version: "3"

services:
  db:
    container_name: mysqldb
    image: mysql:latest
    env_file :
      - ./backend/devenvs/mysqldb.env
    volumes:
     - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - doh      

  backend:
    container_name: backend
    build: ./backend
    command: >
      bash -c "python3 manage.py makemigrations &&
               python3 manage.py migrate &&
               python3 manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - rabbitmq
      - redis
    networks:
      - doh

  ai:
    container_name: ai
    build: ./ai
    command: >
      bash -c "python3 manage.py makemigrations &&
               python3 manage.py migrate &&
               python3 manage.py runserver 0.0.0.0:8081"
    ports:
      - "8081:8081"
    volumes:
      - ./ai:/ai
    depends_on:
      - backend
    networks:
      - doh

  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - doh

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "5672:5672" 
      - "15672:15672"
    expose:
      - "15672"
    networks:
      - doh
    
  celery_worker_1:
    container_name: celery_worker_1
    build:
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend:/backend
    environment:
      - C_FORCE_ROOT=true
    command: sh -c "celery -A backend worker --loglevel=info"
    depends_on:
      - rabbitmq
      - redis
      - backend
    networks:
      - doh

  celery_worker_2:
    container_name: celery_worker_2
    build:
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend:/backend
    environment:
      - C_FORCE_ROOT=true
    command: sh -c "celery -A backend worker --loglevel=info"
    depends_on:
      - rabbitmq
      - redis
      - backend
    networks:
      - doh

volumes:
  mysql_data: {}

networks:
  doh:
    driver: bridge