version: "3"

networks:
  doh:
    driver: bridge

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - ./frontend/:/frontend
      - build_folder:/frontend/dist
      - ./frontend/node_modules/:/frontend/node_modules
    tty: true

  backend:
    container_name: backend
    build: ./backend
    command: >
      bash -c "python3 manage.py makemigrations images &&
               python3 manage.py makemigrations styles && 
               python3 manage.py migrate &&
               gunicorn backend.wsgi --bind 0.0.0.0:8080 --timeout 240"
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - static_volume:/backend/staticfiles
      - media_volume:/backend/mediafiles
    depends_on:
      - rabbitmq
      - redis
    networks:
      - doh

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
#      - "443:443"
    expose:
      - 80
#      - 443
    volumes:
      - static_volume:/backend/staticfiles
      - media_volume:/backend/mediafiles
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend
    networks:
      - doh

  ai:
    container_name: ai
    build: ./ai
    command: >
      bash -c "python3 manage.py makemigrations &&
               python3 manage.py migrate &&
               python3 manage.py runserver 0.0.0.0:8081"
    ports:
      - "8081:8081"
    volumes:
      - ./ai:/ai
    depends_on:
      - backend
    networks:
      - doh

  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - doh

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - "5672:5672" 
      - "15672:15672"
    expose:
      - "15672"
    networks:
      - doh
    
  celery_worker_1:
    container_name: celery_worker_1
    restart: always
    build:
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend:/backend
    environment:
      - C_FORCE_ROOT=true
    command: sh -c "celery -A backend worker --loglevel=info"
    depends_on:
      - rabbitmq
      - redis
      - backend
    networks:
      - doh

  celery_worker_2:
    container_name: celery_worker_2
    restart: always
    build:
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend:/backend
    environment:
      - C_FORCE_ROOT=true
    command: sh -c "celery -A backend worker --loglevel=info"
    depends_on:
      - rabbitmq
      - redis
      - backend
    networks:
      - doh

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - doh


  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    ports:
      - 3100:3000
    environment:
      - GF_SECURITY_ADMIN_USER=root
      - GF_SECURITY_ADMIN_PASSWORD=0707
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    expose:
      - 3100
    networks:
      - doh
      
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - "9200:9100"
    restart: always
    networks:
      - doh

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    networks:
      - doh


  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.46.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8090:8090"
    command:
      - '-port=8090'
    restart: always
    networks:
      - doh
volumes:
  static_volume: null
  media_volume: null
  build_folder: null
  prometheus_data: null
  grafana_data: null
