# Generated by Django 4.0.7 on 2023-01-09 20:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultImage',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default='', max_length=36)),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coordinating',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=36)),
                ('top', models.CharField(max_length=36)),
                ('top_color', models.CharField(max_length=36)),
                ('bottom', models.CharField(max_length=36)),
                ('bottom_color', models.CharField(max_length=36)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.resultimage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
