name: docker CI

on:
  push:
    branches: [ main,feature/#60 ]
  pull_request:
    branches: [ feature/#60 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build
