name: docker CI

on:
  push:
    branches: [ main,feature/#60 ]
  pull_request:
    branches: [ feature/#60 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run a one-line script
      run: echo Hello, world!
