name: docker CI

on:
  push:
    branches: [ main,feature/#60 ]
  pull_request:
    branches: [ feature/#60 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: create env file
        run: |
          touch .env
          echo ${{ secrets.ENV_VARS }} >> .env

      - name: build docker
        run: docker-compose -f docker-compose.prod.yml up --build
